### ISSUE TITLE
How can I custom value on input

### ISSUE THREAD

**Issue by i-ked-ii** [lindomar-oliveira/react-dropdown-cascade#1]
I want to customize value on input look like antd.

<img width="541" alt="Screen Shot 2565-08-10 at 21 28 08" src="https://user-images.githubusercontent.com/23306577/183941152-844a89c0-9ef1-4180-88c0-b3753e3edf68.png">

example:  https://ant.design/components/cascader/#components-cascader-demo-showCheckedStrategy

<img width="476" alt="Screen Shot 2565-08-10 at 22 15 42" src="https://user-images.githubusercontent.com/23306577/183941689-5bf9a8be-a6b6-4ebf-8396-242fc89c6ff8.png">

**Comment by lindomar-oliveira** [comment]
@i-ked-ii I'm sorry for the late reply. If I understand you want to leave the visualization of the chosen value equal to the example of the antd library.

At the current stage, the library does not allow this type of customization, only the `separatorIcon ` which by default is `>`.

**Comment by i-ked-ii** [comment]
In the future I hope to be able to adjust the options as shown in the picture.

<img width="480" alt="Screen Shot 2565-08-26 at 00 07 58" src="https://user-images.githubusercontent.com/23306577/186728191-efff4983-1807-44a5-883d-d777d5f851fb.png">

**Comment by lindomar-oliveira** [comment]
@i-ked-ii Thanks for the sugestion.
